name: Pusblish Mkdocs to GitHub Pages
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Deploy Docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
                uses: actions/checkout@v2
                
            - name: Deploy MkDocs
                uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    CONFIG_FILE: mkdocs.yaml


