site_name: 'KG-Hub Downloader'

repo_name: 'monarch-initiative/kghub-downloader'
repo_url: 'https://github.com/monarch-initiative/kghub-downloader'
docs_dir: docs/

nav: 
    - Home: 'index.md'

theme:
    name: 'material'
